DROP TABLE attendance_data CASCADE;
DROP TABLE department CASCADE;
DROP TABLE employees CASCADE;
DROP TABLE grade CASCADE;
DROP TABLE position CASCADE;
DROP TABLE salary CASCADE;
DROP TABLE salaries_data CASCADE;
DROP TABLE work_schedule CASCADE;