DROP TABLE attendance_data CASCADE;
DROP TABLE departments CASCADE;
DROP TABLE employees CASCADE;
DROP TABLE grades CASCADE;
DROP TABLE positions CASCADE;
DROP TABLE salary CASCADE;
DROP TABLE salaries_data CASCADE;
DROP TABLE work_schedule CASCADE;