CREATE TABLE IF NOT EXISTS DEPARTMENT
(
    ID      int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME    varchar NOT NULL,
    HEAD_ID int4,
    PHONE   varchar,
    EMAIL   varchar,
    ADDRESS varchar
);

CREATE TABLE GRADE
(
    ID    int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    GRADE varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS POSITION
(
    ID            int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    POST          varchar NOT NULL,
    DEPARTMENT_ID int4    NOT NULL REFERENCES DEPARTMENT (ID),
    GRADE_ID      int4    NOT NULL REFERENCES GRADE (ID)
);

CREATE TABLE IF NOT EXISTS SALARIES_DATA
(
    ID           int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    GRADE_ID     int4 NOT NULL REFERENCES grade (ID),
    WAGE         int4 NOT NULL,
    PERSONAL_KPI float4,
    TEAM_KPI     float4,
    COMMON_KPI   float4
);

CREATE TABLE IF NOT EXISTS WORK_SCHEDULE
(
    ID       int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    WORK_DAY int4 NOT NULL,
    WEEK_DAY int4 NOT NULL,
    HOURS    int4 NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPLOYEE
(
--     //Сотрудник: 1, Иванов, Иван, Иванович, мужчина, бухгалтер, бухгалтерия,
--     зп30000, гр5/2, дп2022-11-28, null, null
    ID                int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SURNAME           varchar NOT NULL,
    FIRSTNAME         varchar NOT NULL,
    LASTNAME          varchar NOT NULL,
    GENDER            varchar NOT NULL,
    DEPARTMENT_ID     int4 REFERENCES DEPARTMENT (ID) ON DELETE CASCADE,
    PHONE             varchar,
    EMAIL             varchar,
    POSITION_ID       int4    NOT NULL REFERENCES POSITION (ID) ON DELETE CASCADE,
    SALARY            float4,
    WORK_SCHEDULE_ID  int4    NOT NULL REFERENCES WORK_SCHEDULE (ID) ON DELETE CASCADE,
    DATE_OF_ADMISSION date    NOT NULL,
    DATE_OF_DISMISSAL date
);

ALTER TABLE DEPARTMENT
    ADD CONSTRAINT fk_depHead_to_Employee FOREIGN KEY (HEAD_ID) REFERENCES EMPLOYEE (ID);

CREATE TABLE ATTENDANCE_DATA
(
    ID         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DATE_ATT   date    NOT NULL,
    EMPLOYEE_ID int4    NOT NULL REFERENCES employee (id),
    STATUS    varchar NOT NULL
);

alter table EMPLOYEE
    owner to "BankManager";
alter table POSITION
    owner to "BankManager";
alter table DEPARTMENT
    owner to "BankManager";
alter table SALARIES_DATA
    owner to "BankManager";
alter table WORK_SCHEDULE
    owner to "BankManager";
alter table GRADE
    owner to "BankManager";